test:master:
  image: microsoft/dotnet:2.2-sdk
  stage: test
  script:
    - dotnet test
  only:
    - master

test:tagged:
  image: microsoft/dotnet:2.2-sdk
  stage: test
  script:
    - dotnet build
  except:
    - master