# This file is a template, and might need editing before it works on your project.
# Official docker image.
services:
  - docker:dind

include: 
  - local: .gitlab-ci-build.yml
  - local: .gitlab-ci-deploy.yml

# Targets="win-x64 win-x86 win-arm win-arm64 linux-x64 linux-musl-x64 linux-arm osx-x64"
# for target in $Targets; do
#     dotnet publish -c Release -r $target
# done