build:master:
  image: microsoft/dotnet:2.2-sdk
  stage: build
  script:
    - dotnet build
  only:
    - master

build:tagged:
  image: microsoft/dotnet:2.2-sdk
  stage: build
  script:
    - dotnet build
  except:
    - master