variables:
# Change public image repository name
    DOCKERHUB_REGISTRY_IMAGE: thinkco/ocelot
    
include:
# Comment/Uncomment below this to build and push to local gitlab registry
#  - project: 'thinkcode/devops/templates/pipelines'
#    file: 'build-gitlab-buildah.gitlab-ci.yml'
#    ref: master
# Comment/Uncomment below this to build and push to dockerhub
  - project: 'thinkcode/devops/templates/pipelines'
    file: 'build-dockerhub-buildah.gitlab-ci.yml'
    ref: master
