deploy:docker-master:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy:docker-tagged:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

# Create self-contained executables for supported platforms
# Targets="win-x64 win-x86 win-arm win-arm64 linux-x64 linux-musl-x64 linux-arm osx-x64"
deploy:osx-x64:
  stage: deploy
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet publish -c Release -r osx-x64
    - mv bin/Release/netcoreapp2.2/osx-x64/publish osx-x64
  only:
    - master
  artifacts:
    untracked: false
    name: "osx-x64"
    paths:
      - osx-x64/
    expire_in: 1 week

deploy:win-x64:
  stage: deploy
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet publish -c Release -r win-x64
    - mv bin/Release/netcoreapp2.2/win-x64/publish win-x64
  only:
    - master
  artifacts:
    untracked: false
    name: "win-x64"
    paths:
      - win-x64/
    expire_in: 1 week

deploy:linux-x64:
  stage: deploy
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet publish -c Release -r linux-x64
    - mv bin/Release/netcoreapp2.2/linux-x64/publish linux-x64
  only:
    - master
  artifacts:
    untracked: false
    name: "linux-x64"
    paths:
      - linux-x64/
    expire_in: 1 week

deploy:linux-arm:
  stage: deploy
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet publish -c Release -r linux-arm
    - mv bin/Release/netcoreapp2.2/linux-arm/publish linux-arm
  only:
    - master
  artifacts:
    untracked: false
    name: "linux-arm"
    paths:
      - linux-arm/
    expire_in: 1 week
